/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 16f7bdc4bb0520cddb3179f8dc709ae3)
interface __BaseEnv_Env {
	KV: KVNamespace;
	DB: D1Database;
	EMAIL: SendEmail;
	ASSETS: Fetcher;
	ENVIRONMENT: string;
	BETTER_AUTH_URL: string;
	EMAIL_FROM: string;
	BETTER_AUTH_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/backend/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "BETTER_AUTH_URL" | "EMAIL_FROM" | "BETTER_AUTH_SECRET">> {}
}
